namespace SysCredit.Api.Generators.ErrorCodes;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using System.Linq;
using System.Text;

[Generator]
public class ErrorCodeNumberGenerator : ISourceGenerator
{
    private const string ClassName = "ErrorCodeNumber";

    public void Initialize(GeneratorInitializationContext Context)
    {
    }

    public void Execute(GeneratorExecutionContext Context)
    {
        SourceBuilder Source = SourceBuilder.Create();
        Source.DeclareAutoGenerated()
              .DeclareNamespace(Constants.SysCreditApiConstantsNamespaceName)
              .AddClass(ClassName).Public().Static()
                   .AddConstFieldFactory(ErrorCodeNumberFactory);

        Context.AddSource(Helpers.FileName(ClassName), SourceText.From(Source.Build(), Encoding.UTF8));
    }

    private void ErrorCodeNumberFactory(ClassBuilder Builder)
    {
        foreach (var CodeNumber in Enumerable.Range(Constants.MinCodeNumber, Constants.MaxCodeNumber))
        {
            Builder.AddConstField($"_{CodeNumber,4:D4}").Public().Type("string").Value($"\"{CodeNumber,4:D4}\"");
        }
    }
}
