namespace SysCredit.Api.Generators;

using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using SysCredit.Toolkits.Generators.Extensions;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

/// <inheritdoc />
public partial class InterfaceServiceGenerator
{
    /// <summary>
    ///     Genera la interfaz de la clase de servicio marcado con el atributo ServiceAttribute.
    /// </summary>
    /// <param name="Context">
    ///     Context passed to an incremental generator when it has registered an output via <see cref="IncrementalGeneratorInitializationContext.RegisterSourceOutput{TSource}(IncrementalValueProvider{TSource}, Action{SourceProductionContext, TSource})"/>.
    /// </param>
    /// <param name="Service">
    ///     Información de los métodos de cada servicio que se le va ha generar la interfaz.
    /// </param>
    private static void EmitSourceCode(SourceProductionContext Context, InterfaceServiceInfo Service)
    {
        CompilationUnitSyntax CompilationUnit = SyntaxFactory.CompilationUnit()
            .WithMembers(
                List(new MemberDeclarationSyntax[]
                {
                    NamespaceDeclaration(IdentifierName("SysCredit.Api.Interfaces.Services"))
                        .WithNamespaceKeyword(
                            Token(
                                TriviaList(
                                    Trivia(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), true)
                                        .WithEndOfDirectiveToken(Token(TriviaList(), SyntaxKind.EndOfDirectiveToken, TriviaList(CarriageReturnLineFeed)))),
                                    Trivia(PragmaWarningDirectiveTrivia(Token(SyntaxKind.DisableKeyword), true)
                                        .WithErrorCodes(SingletonSeparatedList<ExpressionSyntax>(IdentifierName("CS1591 // Missing Xml Comment for Publicly Visible Type or Member")))
                                        .WithEndOfDirectiveToken(Token(TriviaList(), SyntaxKind.EndOfDirectiveToken, TriviaList(CarriageReturnLineFeed)))),
                                    Comment("//------------------------------------------------------------------------------"),
                                    Comment("// <auto-generated>                                                             "),
                                    Comment("//     This code was generated by a tool.                                       "),
                                    Comment("//     Runtime Version: 1.0.0.0                                                 "),
                                    Comment("//                                                                              "),
                                    Comment("//     Changes to this file may cause incorrect behavior and will be lost if    "),
                                    Comment("//     the code is regenerated.                                                 "),
                                    Comment("// </auto-generated>                                                            "),
                                    Comment("//------------------------------------------------------------------------------"),
                                    CarriageReturnLineFeed),
                                SyntaxKind.NamespaceKeyword,
                                TriviaList()))
                        .WithUsings(List(Service.Usings))
                        .WithMembers(
                            SingletonList<MemberDeclarationSyntax>(
                                InterfaceDeclaration(Service.InterfaceName)
                                    .WithModifiers(
                                        TokenList(
                                            Token(SyntaxKind.PublicKeyword),
                                            Token(SyntaxKind.PartialKeyword)))
                                    .WithBaseList(
                                        BaseList(SingletonSeparatedList<BaseTypeSyntax>(SimpleBaseType(
                                            GenericName(Identifier("IService")).WithTypeArgumentList(TypeArgumentList(SingletonSeparatedList<TypeSyntax>(IdentifierName(Service.ModelName))))))))
                                    .WithMembers(
                                        List<MemberDeclarationSyntax>(Service.MethodDeclarations)))),
                    NamespaceDeclaration(IdentifierName("SysCredit.Api.Services"))
                        .WithUsings(List(Service.Usings))
                        .WithMembers(SingletonList<MemberDeclarationSyntax>(Service.ClassDeclaration))
                }))
            .WithEndOfFileToken(
                Token(
                    TriviaList(
                        CarriageReturnLineFeed,
                        Trivia(PragmaWarningDirectiveTrivia(Token(SyntaxKind.RestoreKeyword), true)
                            .WithErrorCodes(SingletonSeparatedList<ExpressionSyntax>(IdentifierName("CS1591 // Missing Xml Comment for Publicly Visible Type or Member"))))),
                    SyntaxKind.EndOfFileToken,
                    TriviaList()))
            .NormalizeWhitespace();

        string CSharpText = CompilationUnit.GetText(Encoding.UTF8).ToString();
        Context.AddSource(Helpers.FileName($"SysCredit.Api.Interfaces.Services.{Service.InterfaceName}"), CompilationUnit);
    }
}
