namespace SysCredit.Api.Generators;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using System.Text;

/// <summary>
///     Generador del Api estandar de los códigos de errores para SysCredit.Api.
/// </summary>
internal partial class ErrorCodeGenerator
{
    /// <summary>
    ///     Código fuente de <c>SysCredit.Api.Attributes.ErrorCodePrefixAttribute</c>.
    /// </summary>
    private const string ErrorCodePrefixAttributeSourceCode = """
    //------------------------------------------------------------------------------
    // <auto-generated>                                                             
    //     This code was generated by a tool.                                       
    //     Runtime Version: 1.0.0.0                                                 
    //                                                                              
    //     Changes to this file may cause incorrect behavior and will be lost if    
    //     the code is regenerated.                                                 
    // </auto-generated>                                                            
    //------------------------------------------------------------------------------
    
    namespace SysCredit.Api.Attributes;

    /// <summary>
    ///     Prefijos usados para los códigos de errores: <see cref="SysCredit.Api.Constants.ErrorCodes"/>.
    /// </summary>
    /// <param name="Prefix">
    ///     Prefijo que será usado para los campos de <see cref="SysCredit.Api.Constants.ErrorCodes"/>.
    /// </param>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class ErrorCodePrefixAttribute(string Prefix) : Attribute
    {
        /// <summary>
        ///     Nombre del prefijo usado para la lista de errores en <see cref="SysCredit.Api.Constants.ErrorCodes" />.
        /// </summary>
        public readonly string Prefix = Prefix;
    }
    """;

    /// <summary>
    ///     Código fuente de <c>SysCredit.Api.Attributes.ErrorCodeRangeAttribute</c>.
    /// </summary>
    private const string ErrorCodeRangeAttributeSourceCode = """
    //------------------------------------------------------------------------------
    // <auto-generated>                                                             
    //     This code was generated by a tool.                                       
    //     Runtime Version: 1.0.0.0                                                 
    //                                                                              
    //     Changes to this file may cause incorrect behavior and will be lost if    
    //     the code is regenerated.                                                 
    // </auto-generated>                                                            
    //------------------------------------------------------------------------------
    
    namespace SysCredit.Api.Attributes;
    
    /// <summary>
    ///     Estable el rango mínimo y máximo de los códigos de errores.
    /// </summary>
    /// <param name="MinCodeNumber">
    ///     Número de código de error mínimo.
    /// </param>
    /// <param name="MaxCodeNumber">
    ///     Número de código de error máximo.
    /// </param>
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = false)]
    public class ErrorCodeRangeAttribute(int MinCodeNumber, int MaxCodeNumber) : Attribute
    {
        /// <summary>
        ///     Número de código de error mínimo.
        /// </summary>
        public readonly int MinCodeNumber = MinCodeNumber;
    
        /// <summary>
        ///     Número de código de error máximo.
        /// </summary>
        public readonly int MaxCodeNumber = MaxCodeNumber;
    }
    """;

    /// <summary>
    ///     Crea los atributos usados por este generador.
    /// </summary>
    /// <param name="Context">
    ///     Context passed to an incremental generator when it has registered an output via <see cref="IncrementalGeneratorInitializationContext.RegisterPostInitializationOutput(Action{IncrementalGeneratorPostInitializationContext})" />.
    /// </param>
    private static void GenerateErrorCodeAttributes(IncrementalGeneratorPostInitializationContext Context)
    {
        Context.AddSource(Helpers.FileName("ErrorCodeRangeAttribute"), SourceText.From(ErrorCodeRangeAttributeSourceCode, Encoding.UTF8));
        Context.AddSource(Helpers.FileName("ErrorCodePrefixAttribute"), SourceText.From(ErrorCodePrefixAttributeSourceCode, Encoding.UTF8));
    }
}
