namespace SysCredit.Api.Generators;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using SysCredit.Toolkits.Generators.Extensions;

using System.Collections.Immutable;
using System.Diagnostics;
using System.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

/// <inheritdoc />
internal partial class ErrorCodeGenerator
{
    /// <summary>
    ///     Genera la clase:
    ///     <code>
    ///         // ------------------------------------------------------------------------------
    ///         //  &lt;auto-generated&gt;                                                       
    ///         //      This code was generated by a tool.                                       
    ///         //      Runtime Version: 1.0.0.0                                                 
    ///         //                                                                               
    ///         //      Changes to this file may cause incorrect behavior and will be lost if    
    ///         //      the code is regenerated.                                                 
    ///         //  &lt;/auto-generated&gt;                                                      
    ///         // ------------------------------------------------------------------------------
    ///
    ///         namespace SysCredit.Api.Constants;
    ///
    ///         /// &lt;summary&gt;
    ///         ///     Códigos de error de SysCredit.Api
    ///         /// &lt;summary&gt;
    ///         public static partial class ErrorCodes
    ///         {
    ///             public const string PREFIX0001 = "PREFIX0001";
    ///         }
    ///     </code>
    /// </summary>
    /// <param name="Context">
    ///     Context passed to an incremental generator when it has registered an output via <see cref="IncrementalGeneratorInitializationContext.RegisterSourceOutput{TSource}(IncrementalValueProvider{TSource}, Action{SourceProductionContext, TSource})"/>.
    /// </param>
    /// <param name="Prefixes">
    ///     Prefijos obtenidos desde SysCredit.Api.dll
    /// </param>
    private static void Emit(SourceProductionContext Context, ImmutableArray<string> Prefixes)
    {
        CompilationUnitSyntax CompilationUnit = SyntaxFactory.CompilationUnit()
            .WithMembers(
                SingletonList<MemberDeclarationSyntax>(
                    FileScopedNamespaceDeclaration(
                        QualifiedName(
                            QualifiedName(
                                IdentifierName("SysCredit"), IdentifierName("Api")),
                            IdentifierName("Constants")))
                    .WithNamespaceKeyword(
                        Token(
                            TriviaList(
                                Comment("//------------------------------------------------------------------------------"),
                                Comment("// <auto-generated>                                                             "),
                                Comment("//     This code was generated by a tool.                                       "),
                                Comment("//     Runtime Version: 1.0.0.0                                                 "),
                                Comment("//                                                                              "),
                                Comment("//     Changes to this file may cause incorrect behavior and will be lost if    "),
                                Comment("//     the code is regenerated.                                                 "),
                                Comment("// </auto-generated>                                                            "),
                                Comment("//------------------------------------------------------------------------------")),
                            SyntaxKind.NamespaceKeyword,
                            TriviaList()))
                    .WithMembers(
                        SingletonList<MemberDeclarationSyntax>(
                            ClassDeclaration("ErrorCodes")
                            .WithModifiers(
                                TokenList(
                                    Token(
                                        TriviaList(
                                            Comment("/// <summary>"),
                                            Comment("///     Códigos de error de SysCredit.Api"),
                                            Comment("/// <summary>")),
                                        SyntaxKind.PublicKeyword,
                                        TriviaList()),
                                    Token(SyntaxKind.StaticKeyword),
                                    Token(SyntaxKind.PartialKeyword)))
                            .WithMembers(
                                List<MemberDeclarationSyntax>(GetFieldDeclarationSyntaxes(Prefixes)))))))
            .NormalizeWhitespace();

        string CSharpText = CompilationUnit.GetText(Encoding.UTF8).ToString();
        Context.AddSource(Helpers.FileName("ErrorCodes"), CompilationUnit);
    }

    private static IEnumerable<FieldDeclarationSyntax> GetFieldDeclarationSyntaxes(ImmutableArray<string> CodePrefixes)
    {
        // Construct the generated field as follows:
        // public const string <CodePrefix><CodeNumber> = "<CodePrefix><CodeNumber>";

        foreach (var CodePrefix in CodePrefixes)
        {
            foreach (var CodeNumber in Enumerable.Range(Constants.MinCodeNumber, Constants.MaxCodeNumber))
            {
                yield return FieldDeclaration(
                                VariableDeclaration(PredefinedType(Token(SyntaxKind.StringKeyword)))
                                .WithVariables(
                                    SingletonSeparatedList(
                                        VariableDeclarator($"{CodePrefix}{CodeNumber}")
                                            .WithInitializer(EqualsValueClause(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal($"{CodePrefix}{CodeNumber}")))))))
                             .WithModifiers(
                                TokenList(
                                    Token(
                                        TriviaList(
                                            Comment("/// <summary>"),
                                            Comment("///     Código de error para la categoría: ???"),
                                            Comment("/// <summary>")),
                                        SyntaxKind.PublicKeyword,
                                        TriviaList()),
                                    Token(SyntaxKind.ConstKeyword)))
                             .WithSemicolonToken(Token(SyntaxKind.SemicolonToken));
            }
        }
    }
}
