INSERT INTO `Relationship` (`RelationshipId`, `Name`) 
VALUES (1, 'Papá'),
       (2, 'Mamá'),
       (3, 'Hermano'),
       (4, 'Hermana'),
       (5, 'Tío'),
       (6, 'Tía'),
       (7, 'Sobrino'),
       (8, 'Sobrina'),
       (9, 'Nieto'),
       (10, 'Nieta'),
       (11, 'Esposo'),
       (12, 'Esposa'),
       (13, 'Hijo'),
       (14, 'Hija'),
       (15, 'Primo'),
       (16, 'Prima'),
       (17, 'Abuelo'),
       (18, 'Abuela'),
       (19, 'Amigo'),
       (20, 'Amiga'),
       (21, 'Cuñado'),
       (22, 'Cuñada'),
       (23, 'Padrasto'),
       (24, 'Madrasta'),
       (25, 'Novio'),
       (26, 'Novia')
ON DUPLICATE KEY UPDATE `Name` = VALUES(`Name`);